[script] sync make-pretty scripts from openthread (#29)
- Also reformat files.

diff --git a/script/clang-format b/script/clang-format
--- a/script/clang-format
+++ b/script/clang-format
@@ -26,69 +26,45 @@
 #  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 #  POSSIBILITY OF SUCH DAMAGE.
 #
-#    Description:
-#      This file runs various tests.
-#
 
-set -e
-set -o pipefail
+CLANG_FORMAT_VERSION="clang-format version 6.0"
 
-readonly BUILD_JOBS="$(getconf _NPROCESSORS_ONLN)"
-readonly BUILD_DIR=build
-readonly PLATFORM_NAME="${PLATFORM:-nrf52}"
-
-readonly COLOR_PASS='\033[0;32m'
-readonly COLOR_FAIL='\033[0;31m'
-readonly COLOR_NONE='\033[0m'
-
-do_clean() {
-    [[ ! -d "${BUILD_DIR}" ]] || rm -rvf "${BUILD_DIR}"
+die() {
+    echo " *** ERROR: $*"
+    exit 1
 }
 
-do_build() {
-    [[ -d "${BUILD_DIR}" ]] || mkdir "${BUILD_DIR}"
-    (cd "${BUILD_DIR}" && cmake .. "$@" && make -j${BUILD_JOBS})
+if command -v clang-format-6.0 > /dev/null; then
+    alias clang-format=clang-format-6.0
+elif command -v clang-format > /dev/null; then
+    case "$(clang-format --version)" in
+        "$CLANG_FORMAT_VERSION"*)
+            ;;
+        *)
+            die "$(clang-format --version); clang-format 6.0 required"
+            ;;
+    esac
+else
+    die "clang-format 6.0 required"
+fi
+
+clang-format "$@" || die
+
+# ensure EOF newline
+REPLACE=no
+for arg
+do
+    case $arg in
+        -i)
+            REPLACE=yes
+            ;;
+    esac
+done
+
+file=$arg
+
+[ $REPLACE != yes ] || {
+    [ -n "$(tail -c1 "$file")" ] && echo >> "$file"
 }
 
-print_usage() {
-    cat <<EOF
-USAGE: $0 COMMAND
-
-COMMAND:
-    build       Build project for running tests. This can be used to rebuild the project for changes.
-    clean       Clean built files to prepare new build.
-    help        Print this help.
-
-EXAMPLES:
-    $0 clean build
-EOF
-    exit "$1"
-}
-
-main()
-{
-    while [[ -n "$1" ]]; do
-        case "$1" in
-            clean)
-                do_clean
-                ;;
-            build_linux)
-                do_clean
-                do_build -DPLATFORM_NAME=linux
-                ;;
-            build_nrf52840)
-                do_clean
-                do_build -DCMAKE_TOOLCHAIN_FILE=../cmake/arm-none-eabi.cmake -DPLATFORM_NAME=nrf52
-                ;;
-            help)
-                print_usage
-                ;;
-            *)
-                print_usage 1
-                ;;
-        esac
-        shift
-    done
-}
-
-main "$@"
+exit 0
diff --git a/script/clang-format-check b/script/clang-format-check
--- a/script/clang-format-check
+++ b/script/clang-format-check
@@ -26,69 +26,25 @@
 #  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 #  POSSIBILITY OF SUCH DAMAGE.
 #
-#    Description:
-#      This file runs various tests.
+
+#
+# clang-format does not return a non-zero exit code.  This wrapper
+# exits with a non-zero exit code if clang-format outputs any
+# replacements.
 #
 
-set -e
-set -o pipefail
+set -euo pipefail
 
-readonly BUILD_JOBS="$(getconf _NPROCESSORS_ONLN)"
-readonly BUILD_DIR=build
-readonly PLATFORM_NAME="${PLATFORM:-nrf52}"
-
-readonly COLOR_PASS='\033[0;32m'
-readonly COLOR_FAIL='\033[0;31m'
-readonly COLOR_NONE='\033[0m'
-
-do_clean() {
-    [[ ! -d "${BUILD_DIR}" ]] || rm -rvf "${BUILD_DIR}"
+die() {
+    echo " *** ERROR:  $*"
+    exit 1
 }
 
-do_build() {
-    [[ -d "${BUILD_DIR}" ]] || mkdir "${BUILD_DIR}"
-    (cd "${BUILD_DIR}" && cmake .. "$@" && make -j${BUILD_JOBS})
-}
+# from `man diff`:
+# Exit status is 0 if inputs are the same, 1 if different, 2 if trouble.
 
-print_usage() {
-    cat <<EOF
-USAGE: $0 COMMAND
-
-COMMAND:
-    build       Build project for running tests. This can be used to rebuild the project for changes.
-    clean       Clean built files to prepare new build.
-    help        Print this help.
-
-EXAMPLES:
-    $0 clean build
-EOF
-    exit "$1"
-}
-
-main()
-{
-    while [[ -n "$1" ]]; do
-        case "$1" in
-            clean)
-                do_clean
-                ;;
-            build_linux)
-                do_clean
-                do_build -DPLATFORM_NAME=linux
-                ;;
-            build_nrf52840)
-                do_clean
-                do_build -DCMAKE_TOOLCHAIN_FILE=../cmake/arm-none-eabi.cmake -DPLATFORM_NAME=nrf52
-                ;;
-            help)
-                print_usage
-                ;;
-            *)
-                print_usage 1
-                ;;
-        esac
-        shift
-    done
-}
-
-main "$@"
+for file in "$@"; do
+    echo "Checking ${file}"
+    "$(dirname "$0")"/clang-format -style=file "${file}" | diff -u "${file}" - || die "${file} is not pretty."
+    [ -z "$(tail -c1 "${file}")" ] || die "${file} misses EOF newline."
+done
